### ISSUE TITLE
$_POST variable using

### ISSUE THREAD

**Issue by OlenaTatarintseva** [emeneo/moodle-blocks_coursereport#1]
Hello,

First of all I want to say thank you for your work with the plugin.

I reviewed the code and found $_POST variable using in blocks/report_free_seats/generate_report.php. It would be better to use optional_param() or required_param() instead.

Best regards,
Olena Tataritnseva

**Comment by Flottertotte** [comment]
Hello Olena,

Thank you! Would it be possible for you to send a pull request for that? It sounds useful!

Greetings, Flotter

**Comment by Flottertotte** [comment]
Thanks for reporting, the bug has been fixed.
